obj-m += fbdbi.o

# lcdreg
#obj-$(CONFIG_LCDREG)             += lcdreg.o
#obj-$(CONFIG_LCDREG_SPI)         += lcdreg-spi.o
#obj-$(CONFIG_LCDREG_PAR)         += lcdreg-par.o
obj-m += lcdreg.o
obj-m += lcdreg-spi.o
obj-m += lcdreg-par.o
obj-m += lcdreg-i80.o
